spring.application.name=exp5

server.port=8080

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info